[package]
name = "decimal64"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "TBC"
readme = "./README.md"
documentation = "https://docs.rs/decimal64"
repository = "https://github.com/HaveFunTrading/decimal64"

[dependencies]
